### PR TITLE
A few to start with.

### PR DESCRIPTION
**Pull request by JKReynolds**
**These are some proposed use cases**
Job Applications
Resume Builders
Calendar Applications
Message Applications
Car insurance Applications
Apartment Rental Applications
Loan Applications

### CODE REVIEW

**Comment by JKReynolds** [comment]
My team and I put together a couple use cases that we would like to get some feedback on. Please let us know what you think. Thanks.

**Comment by dmitrizagidulin** [comment]
While we're talking about this, I do want to bring up PR https://github.com/solid/identity-panel/issues/1 which (among other things) proposes that we should separate 'user info' type data (most of which is private / access-controlled) from the public WebID profile doc.

**Comment by dmitrizagidulin** [comment]
(Which also echoes what @justinwb is saying in the previous comment, "information that should be discoverable via someone's user profile, not contained inside of it")

**Comment by mark-jensen** [comment]
@justinwb @dmitrizagidulin  I am not sure I understand the distinction between data being discoverable via a user profile vs. being contained in it. The distinction seems to track one between public vs private, but if the private data is merely discoverable via a user profile, where is it "contained"?

**Comment by mark-jensen** [comment]
We have posted initial components for the User Profile use case described in this PR ([link](https://github.com/solid/data-interoperability-panel/blob/49bf3b2debfbe20af6fe97b9fc0dee4b9558300c/user-profile/use-cases.md)), as well as in #24, to a project repository located [here](https://github.com/CommonCoreOntology/UserProfileOntology)

Thus far we have:

- User Profile Ontology module which extends CCO
- Sample batch of RDF for a profile
- An example of a shape for person's full name and nickname
- A spreadsheet of relevant ontology terms and definitions

Some members of our team will attend Monday's (10/21) Data Interoperability Panel call to provide a brief overview, discuss and answer questions.

**Comment by elf-pavlik** [comment]
We are going to merge this PR and move contributed file to `archive` directory. If you would like to continue this work please join [panel meeting](https://github.com/solid/data-interoperability-panel#meetings) to discuss way forward.

**Pull request merged**
